site_name: Aetous' Blog
site_description: One stop infodump about all of Aetous' creative endeavors!
site_author: Aetous
site_url: https://aeto.us
docs_dir: aetous-vrc-blog
theme:
  name: bootstrap
  custom_dir: overrides
plugins: 
  - search
  - redirects:
      redirect_maps:
        'omni.md': 'Worlds/Omni.md'
        'abg.md': 'Worlds/Abstract Backyard Glow.md'
extra_css:
  - css/custom.css