site_name: Aetous' Blog
site_description: One stop infodump about all of Aetous' creative endeavors!
site_author: Aetous
theme:
  name: bootstrap
  custom_dir: overrides
plugins: 
  - search
extra_css:
  - css/custom.css